import Head from 'next/head'
import { Poppins } from '@next/font/google'
import { NextPage } from 'next'

const poppins = Poppins({ weight: '400', subsets: ['latin'] })

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  )
}

export default Home
